### ISSUE TITLE
Woes of the staging environment

### ISSUE THREAD

**Issue by jonnalley** [HHS/OPRE-OPS#726] opened 2023-03-09 03:36 UTC
The staging environment appears to have a few issues related to deployment

## Expected Behavior
When a branch is pushed to `staging`, it is expected to see the changes in that branch successfully deployed in `staging` including application and data-tools running successfully. It's also expected to be able to log in to the login.gov sandbox environment error free. 

## Current Behavior
* It appears that changes being deployed to `staging` are not truly deployed successfully in that cloud.gov space. 
* Currently when trying to sign in from OPS, login.gov thinks you are signing in to OPS `development`, not `staging`. After attempting to sign in anyway, the user is redirected to the staging environment, but not logged in. On Tuesday at least, login.gov was returning an error that the redirect_uri doesn't match. See attached video for a demo.https://images.zenhubusercontent.com/368634076/21d2791c-e76e-498f-900c-64dd18a54ad1/staging_is_borked.mov

## Steps to Reproduce
1. Push a branch to staging using the instructions in the README.

**Comment by tdonaworth** [comment] 2023-03-09 13:55
This was actually an issue in the environment configuration itself. This was fixed with no code changes. 

Root cause, the private key was stored in the wrong format, so login was failing on JWT creation.

This can/should be resolved with a proper IaC Config Mgmt setup (Terraform?). 

This only resolves the deployment issue, and not other existing bugs in all release versions.

**Closed by tdonaworth** 2023-03-09 13:55 UTC
Labels: bug

**Comment by jonnalley** [comment] 2023-03-09 17:18
@tdonaworth thanks I am seeing an improvement, but the login.gov UI is still saying it's logging you into "OPRE OPS DEV".  Is that just a limitation of the fact that we have one sandbox ?  It does actually log you into staging without issue though.
