### ISSUE TITLE
update OpenApi spec for the `/can-funding-summary` endpoint

### ISSUE THREAD

**Issue by fpigeonjr** [HHS/OPRE-OPS#3048] opened 2024-11-08 16:16 UTC
![Image](https://github.com/user-attachments/assets/c370e402-673c-4d4f-9fde-043dcebef3ca)

**Comment by maiyerlee** [comment] 2024-12-10 18:52
I think this is a duplicate of https://github.com/HHS/OPRE-OPS/issues/2961

**Closed by maiyerlee** 2024-12-10 18:52 UTC
Labels: tech-debt
