### ISSUE TITLE
Remove 3 cards from bottom of Agreement Details

### ISSUE THREAD

**Issue by kimschulke** [HHS/OPRE-OPS#1875] opened 2024-01-16 20:52 UTC
### Goals
* Update the summary cards to match more recent design changes
* Remove the 3 summary cards at the bottom which have been replaced by the 2 summary cards at the top

### Tasks
- [ ]

### Additional Context
*This update also needs to be made on the Create Agreement workflow. It can likely be taken care of when we are updating the Create Agreement workflow to include SCs

**Comment by kimschulke** [comment] 2024-01-16 20:53
<img width="1022" alt="Screenshot 2024-01-16 at 3 12 56 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/008a9f6f-f367-4312-b236-9d57945fba26">

**Comment by kimschulke** [comment] 2024-01-16 20:58
Link to updated designs in Figma: https://www.figma.com/file/dsQFe6G2KjcTWNq7NNZujm/OPRE-OPS?type=design&node-id=6175%3A44166&mode=design&t=yfyrMxkq9YNGXGIA-1

<img width="693" alt="Screenshot 2024-01-16 at 3 58 04 PM" src="https://github.com/HHS/OPRE-OPS/assets/65555918/4e9deceb-1ae5-4806-ad3b-e43c3379e7e8">

**Comment by jonnalley** [comment] 2024-01-17 03:43
@kimschulke This is a dupe of #1559. I'll move the figma links over though.

**Closed by jonnalley** 2024-01-17 03:43 UTC
Labels: bug, design-debt, Improvement
